const { PDFDocument, StandardFonts, rgb } = require('pdf-lib');

const currency = (value = 0) => `Rs. ${Math.round(value).toLocaleString('en-IN')}`;
const formatDate = (date) =>
  new Date(date).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });

const drawText = (page, text, x, y, options = {}) => {
  page.drawText(String(text || '-'), {
    x,
    y,
    size: options.size || 10,
    font: options.font,
    color: options.color || rgb(0.15, 0.18, 0.24)
  });
};

const generateCertificate = async (user, incomeData, period) => {
  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([595, 842]);
  const bold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
  const regular = await pdfDoc.embedFont(StandardFonts.Helvetica);

  page.drawRectangle({ x: 0, y: 742, width: 595, height: 100, color: rgb(0.11, 0.31, 0.85) });
  drawText(page, 'INCOME CERTIFICATE', 48, 790, { size: 24, font: bold, color: rgb(1, 1, 1) });
  drawText(page, 'Self-Employed / Gig Economy Worker', 48, 768, { size: 12, font: regular, color: rgb(1, 1, 1) });

  let y = 705;
  drawText(page, 'Worker details', 48, y, { size: 14, font: bold });
  y -= 28;

  const rows = [
    ['Name', user.name],
    ['Phone', user.phone],
    ['City', user.city || '-'],
    ['Vehicle type', user.vehicleType || 'none'],
    ['Working since', user.workingSince ? formatDate(user.workingSince) : '-']
  ];

  rows.forEach(([label, value]) => {
    drawText(page, label, 60, y, { font: bold });
    drawText(page, value, 210, y, { font: regular });
    y -= 22;
  });

  y -= 16;
  drawText(page, 'Income summary', 48, y, { size: 14, font: bold });
  y -= 28;

  const summaryRows = [
    ['Period covered', `${formatDate(incomeData.startDate)} to ${formatDate(incomeData.endDate)}`],
    ['Total gross income', currency(incomeData.totalGross)],
    ['Average monthly income', currency(incomeData.avgMonthly)],
    ['Total transactions', incomeData.entryCount]
  ];

  summaryRows.forEach(([label, value]) => {
    drawText(page, label, 60, y, { font: bold });
    drawText(page, value, 210, y, { font: regular });
    y -= 22;
  });

  y -= 18;
  drawText(page, 'Platform breakdown', 48, y, { size: 14, font: bold });
  y -= 26;
  page.drawRectangle({ x: 48, y: y - 6, width: 500, height: 24, color: rgb(0.93, 0.96, 1) });
  drawText(page, 'Platform', 60, y, { font: bold });
  drawText(page, 'Total Earned', 255, y, { font: bold });
  drawText(page, '% of Income', 420, y, { font: bold });
  y -= 28;

  incomeData.byPlatform.forEach((row) => {
    drawText(page, row.platform, 60, y, { font: regular });
    drawText(page, currency(row.total), 255, y, { font: regular });
    drawText(page, `${row.percentage.toFixed(1)}%`, 420, y, { font: regular });
    y -= 22;
  });

  page.drawLine({ start: { x: 48, y: 84 }, end: { x: 548, y: 84 }, thickness: 1, color: rgb(0.75, 0.8, 0.88) });
  drawText(
    page,
    `This certificate is generated by GigLedger (gigledger.in) based on income data self-reported by the worker.`,
    48,
    62,
    { size: 8, font: regular }
  );
  drawText(
    page,
    `It is not a government-issued document. Generated on ${formatDate(new Date())}.`,
    48,
    48,
    { size: 8, font: regular }
  );

  const bytes = await pdfDoc.save();
  return Buffer.from(bytes);
};

module.exports = { generateCertificate };
