import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: { padding: 36, fontSize: 11, color: '#1f2937' },
  header: { backgroundColor: '#1d4ed8', color: '#ffffff', padding: 18, marginBottom: 24 },
  title: { fontSize: 22, marginBottom: 4 },
  section: { marginBottom: 18 },
  heading: { fontSize: 14, marginBottom: 8 },
  row: { flexDirection: 'row', paddingVertical: 3 },
  label: { width: 150, fontWeight: 700 },
  footer: { borderTopWidth: 1, borderTopColor: '#cbd5e1', paddingTop: 10, marginTop: 20, fontSize: 8 }
});

const rupees = (value) => `Rs. ${Math.round(value || 0).toLocaleString('en-IN')}`;

const IncomeCertificatePDF = ({ user, incomeData }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.header}>
        <Text style={styles.title}>INCOME CERTIFICATE</Text>
        <Text>Self-Employed / Gig Economy Worker</Text>
      </View>
      <View style={styles.section}>
        <Text style={styles.heading}>Worker details</Text>
        <View style={styles.row}><Text style={styles.label}>Name</Text><Text>{user?.name}</Text></View>
        <View style={styles.row}><Text style={styles.label}>Phone</Text><Text>{user?.phone}</Text></View>
        <View style={styles.row}><Text style={styles.label}>City</Text><Text>{user?.city || '-'}</Text></View>
      </View>
      <View style={styles.section}>
        <Text style={styles.heading}>Income summary</Text>
        <View style={styles.row}><Text style={styles.label}>Total gross income</Text><Text>{rupees(incomeData?.totalGross)}</Text></View>
        <View style={styles.row}><Text style={styles.label}>Average monthly income</Text><Text>{rupees(incomeData?.avgMonthly)}</Text></View>
      </View>
      <View style={styles.footer}>
        <Text>This certificate is generated by GigLedger based on self-reported income data.</Text>
      </View>
    </Page>
  </Document>
);

export default IncomeCertificatePDF;
